### PR TITLE
Automate

### LINKED ISSUE #1: Add new icons automatically
See [here](https://github.com/elm-community/elm-material-icons/issues/3).

### PR DESCRIPTION
**Pull request by icidasset**
Closes #1 
Uses https://github.com/google/material-design-icons

Thanks for this library by the way 👍 
I wanted to add those new icons.

Let me know if I messed something up 😅

### CODE REVIEW

**Comment by mgold** [comment]
Sweet! This looks amazing! 

But there are a few places where it's not compiling because it looks like it's grabbed SVG markup instead of the path. Can you fix those and make sure `elm make` passes please?

**Comment by icidasset** [comment]
Woops, sorry about that. Ok, this was a lot more difficult than I initially thought 😅  But I think I got it now. The difficult part, as you probably know, is that not all icons are a single path (unlike fontawesome).

Scenarios:
1. Multiple`path` nodes (with sometimes a `fill-opacity` attribute)
2. Multiple `circle` nodes
3. Combination of 1 & 2

I don't know if I missed any scenarios.
Probably should write something to check that 🤔 

Anyhow, I solved this by changing the `icon` function which now takes a list of `Svg msg`s, and I've used some serious Bash scripting magic. _I should've probably used Ruby or whatever instead, because this is getting messy._

Thoughts?

EDIT: We should probably generate a sample html document with all the icons in it so we can verify that the icons look the same.

**Comment by mgold** [comment]
Looking a lot better!

I actually don't know much about all the different combinations of paths, circles, and so on, so I'm hoping 

> I should've probably used Ruby or whatever instead, because this is getting messy.

I :heart: ruby, so if you wanted to put to work into converting the script, I think it would make some of these functions easier to write and maybe test.

> We should probably generate a sample html document with all the icons in it so we can verify that the icons look the same.

Good idea! Why don't you open a separate issue?

I ran `elm package diff` to see what's changed and there are a few removed icons that appear to still be present in the source of truth. A few of these discrepancies are typos on our end (`thumps_up_down`, smh) but others seem to be pluralization or number conversion errors. (I have zero problem with a ruby script depending on ActiveSuport.) There's also a lot of odd removals in `Material.Icons.Device`.

I'd like to avoid as many renames as possible, even if we can't avoid all of them. How much of this do you want to tackle?

**Comment by icidasset** [comment]
I just rewrote it in ruby, sooo much better 😄 

Changes:
- It's easier to understand what's going on.
- It's faster (who would've thought?)
- Now uses a "lookup table" to translate icon names
    - You can use this to keep some of the old icon names
    - Gives an error when an icon name starts with a number
       and isn't in the lookup table.
- Now uses functions to process nodes, so you can easily process other nodes.
   Like we do with `circle`s.
- Now detects if we forgot to process certain nodes.

Thanks, I didn't know about `elm package diff`, I added a few entries to the lookup table.
Can you check again? By the way, when I compare it with https://material.io/icons/, it seems like the `Device.signal_wifi_statusbar_*` icons have been removed.

**Comment by mgold** [comment]
Awesome!!

> It seems like the Device.signal_wifi_statusbar_* icons have been removed.

They seem to still be [here](https://github.com/google/material-design-icons/tree/master/device/svg/production)? Same with [star rate](https://github.com/google/material-design-icons/blob/master/action/svg/production/ic_star_rate_18px.svg). Maybe the icons have weird names or aren't the standard size? If it's an upstream problem, or if the icons have been deprecated but the source is still around, I could consider dropping them.

**Comment by icidasset** [comment]
Huh weird, ok, thanks! I'll slightly adjust the generator to include them.

**Comment by icidasset** [comment]
Aight cool, it now accounts for icons with different sizes.

Changes:
- You must pass the `viewBox` attribute value to the `icon` function (__internally that is__)
- It loops over all svg files and if that icon isn't in the collection yet, then it adds it.
   - Possible downside: This means that it takes the first icon that it finds, which is the smallest version of the icon. Should we prefer the 24px version? Or is this ok?

The only removal now is the icon with the typo (ie. `thumps_up_down`) 👍

**Comment by mgold** [comment]
I think it should prefer the largest-sized icon available, if that's not too hard.

**Comment by icidasset** [comment]
Done 👍

**Comment by mgold** [comment]
Looks good! Thank you so much!

**Pull request merged**
